### ISSUE TITLE
파일명이랑 확장자가 이상해요

### ISSUE THREAD

**Issue by shinwonse** [ssumthingood/project-skeleton#1]
jsx 문법 사용 중인 파일은 jsx로 확장자 해주시고 pages 디렉토리의 페이지 파일명은 소문자로 하세요. 그리고 CRA 쓰시지 마시고 그냥 리액트만 쓰고 싶으시면 vite 쓰십쇼

**Comment by ssumthingood** [comment]
오홍 피드백 ㄱㅅㄱㅅ 일할때 그렇게함??

**Comment by shinwonse** [comment]
일할 때는 당연히 그렇게하고 그냥 저게 국룰입니다. 다른 사람들 프로젝트들 열심히 참고해보시길

**Comment by shinwonse** [comment]
그리고 자스말고 무조건 타스 쓰시고 리액트 최근 문서 들어가보면 CRA 안씁니다

**Comment by ssumthingood** [comment]
올만에 뭐 만들어보니 많이바꼈네 다시 공부해야지 ㄱㅅㄱㅅ
